services:
  perfume-tracker:
    image: adamsarok/perfume-tracker
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_R2_API_ADDRESS=${NEXT_PUBLIC_R2_API_ADDRESS}
      - NEXT_PUBLIC_PERFUMETRACKER_API_ADDRESS=${PERFUMETRACKER_API_ADDRESS}
    restart: unless-stopped
    build:
       context: ./perfumetracker.client/
       dockerfile: Dockerfile
  perfume-tracker-api:
    image: adamsarok/perfume-tracker-api
    ports:
      - 7080:8080
      - 7081:8081
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    restart: unless-stopped
    build:
      context: .
      dockerfile: PerfumeTracker.Server/Dockerfile