services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: perfumetracker
    ports:
      - "5432:5432"

  r2-api-go:
    image: fuzzydice555/r2-api-go
    ports:
          - 9088:8080
    environment:
          - R2_ENDPOINT=
          - R2_BUCKET=
          - R2_REGION=auto
          - R2_ACCESS_KEY=
          - R2_SECRET_KEY=
          - R2_UPLOAD_EXPIRY_MINUTES=30
          - R2_DOWNLOAD_EXPIRY_MINUTES=30
    restart: unless-stopped

  perfume-tracker:
      image: fuzzydice555/perfume-tracker
      ports:
        - 3000:3000
      environment:
        - DATABASE_URL=postgresql://postgres:password@db:5432/perfumetracker
        - R2_API_ADDRESS=http://localhost:9088
      restart: unless-stopped
      depends_on:
        - db
        - r2-api-go