import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Perfume Tracker",
  description: "Generated by create next app",
};

//TODO: fix all page layouts for mobile
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer position="top-right" />
        <div className="max-w-lg mx-auto px-4 py-8">
          <div className="flex items-center space-x-2 mb-2">
            <a className="menuButton" color="foreground" href="/">
              Home
            </a>
            <a className="menuButton" color="foreground" href="/perfumes/surprise-me">
              Surprise me!
            </a>
            <a className="menuButton" color="foreground" href="/perfumes/new-perfume">
              New Perfume
            </a>
            <a className="menuButton" color="foreground" href="/perfumes">
              Perfumes
            </a>
          </div>
          <div className="flex items-center space-x-2">
            <a className="menuButton" color="foreground" href="/stats">
              Stats
            </a>
            <a className="menuButton" color="foreground" href="/calendar">
              Calendar
            </a>
            <a className="menuButton" color="foreground" href="/tags">
              Tags
            </a>
            <a className="menuButton" color="foreground" href="/recommendations">
              Recommendations
            </a>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
