import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Perfume Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light light:bg-zinc-50 light:text-black bg-black text-white">
      <body className={inter.className}>
        <ToastContainer position="top-right"/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
